const Fuse = require('fuse.js');
const CATEGORY_MAP = {
    "food": "Food & Basic Needs",
    "pantry": "Food & Basic Needs",
    "pantries": "Food & Basic Needs",
    "groceries": "Food & Basic Needs",
    "meals": "Food & Basic Needs",
    "bank": "Food & Basic Needs",
    "shelter": "Food & Basic Needs",
    "shelters": "Food & Basic Needs",
    "homeless": "Food & Basic Needs",
    "hospital": "Healthcare & Mental Health",
    "hospitals": "Healthcare & Mental Health",
    "clinic": "Healthcare & Mental Health",
    "clinics": "Healthcare & Mental Health",
    "doctor": "Healthcare & Mental Health",
    "doctors": "Healthcare & Mental Health",
    "medical": "Healthcare & Mental Health",
    "health": "Healthcare & Mental Health",
    "mental": "Healthcare & Mental Health",
    "therapy": "Healthcare & Mental Health",
    "counseling": "Healthcare & Mental Health",
    "library": "Education & Libraries",
    "libraries": "Education & Libraries",
    "books": "Education & Libraries",
    "school": "Education & Libraries",
    "schools": "Education & Libraries",
    "education": "Education & Libraries",
    "job": "Government & Legal Services",
    "jobs": "Government & Legal Services",
    "career": "Government & Legal Services",
    "careers": "Government & Legal Services",
    "resume": "Government & Legal Services",
    "employment": "Government & Legal Services",
    "legal": "Government & Legal Services",
    "lawyer": "Government & Legal Services",
    "lawyers": "Government & Legal Services",
    "attorney": "Government & Legal Services",
    "attorneys": "Government & Legal Services",
    "youth": "Community & Recreation",
    "family": "Community & Recreation",
    "families": "Community & Recreation",
    "kids": "Community & Recreation",
    "child": "Community & Recreation",
    "children": "Community & Recreation",
    "senior": "Community & Recreation",
    "seniors": "Community & Recreation",
    "aging": "Community & Recreation",
    "elderly": "Community & Recreation",
    "community": "Community & Recreation",
    "recreation": "Community & Recreation",
    "park": "Community & Recreation",
    "parks": "Community & Recreation",
    "pool": "Community & Recreation",
    "restaurant": "Restaurants",
    "restaurants": "Restaurants",
    "dining": "Restaurants",
    "eat": "Restaurants",
    "cafe": "Restaurants"
};
const keys = Object.keys(CATEGORY_MAP);
const fuse = new Fuse(keys, { threshold: 0.4 });
console.log(fuse.search("college"));
